#note it seems this can only be 1 level deep
cache_expiry:
  production: 86400 
  development: 2000
cache_prefix: bss
mau_api_url: 
  production: http://missionartistsunited.org/api
  development: http://missionartistsunited.org/api
  test: http://test.mau.org/api
mau_web_url: 
  production: http://missionartistsunited.org/
  development: http://missionartistsunited.org/
  test: http://test.mau.org/
database_url:
  test: "postgres://localhost/bryant_test"
  development: "postgres://localhost/bryant_dev"
auth_user:
  test: whatever
  development: whatever
auth_pass:
  test: whatever
  development: whatever

  