#note it seems this can only be 1 level deep
cache_expiry:
  production: 86400 
  development: 20
cache_prefix: bss
mau_api_url: http://missionartistsunited.org/api
mau_web_url: http://missionartistsunited.org

auth_user:
  test: whatever
  development: whatever
auth_pass:
  test: whatever
  development: whatever

  