#note it seems this can only be 1 level deep
cache_expiry:
  production: 86400 
  development: 20
cache_prefix: bss
mau_api_url: http://missionartistsunited.org/api
mau_web_url: http://missionartistsunited.org

database_url:
  test: "postgres://localhost/bryant_test"
  development: "postgres://localhost/bryant_dev"
auth_user:
  test: whatever
  development: whatever
auth_pass:
  test: whatever
  development: whatever

  