require_relative "./art_piece.rb"
require_relative "./artist_exclusions.rb"
require_relative "./artists.rb"
require_relative "./content.rb"
require_relative "./mediums.rb"
require_relative "./pictures.rb"
require_relative "./studio.rb"
